// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3FKlferzd_jA4n7dRRyNm5F0ty9s4fs',
    appId: '1:497229688858:web:ea6d98385460a190fba1a3',
    messagingSenderId: '497229688858',
    projectId: 'finance-app-85342',
    authDomain: 'finance-app-85342.firebaseapp.com',
    storageBucket: 'finance-app-85342.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrGUSAW-430FbdfiM2hjfsKoU-KjMfUYc',
    appId: '1:497229688858:android:3b897549c30c8c98fba1a3',
    messagingSenderId: '497229688858',
    projectId: 'finance-app-85342',
    storageBucket: 'finance-app-85342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPDZXV8TVWkLjtp9HWDx2okErnEhyEDM',
    appId: '1:497229688858:ios:d14f273bc97f669efba1a3',
    messagingSenderId: '497229688858',
    projectId: 'finance-app-85342',
    storageBucket: 'finance-app-85342.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPDZXV8TVWkLjtp9HWDx2okErnEhyEDM',
    appId: '1:497229688858:ios:d14f273bc97f669efba1a3',
    messagingSenderId: '497229688858',
    projectId: 'finance-app-85342',
    storageBucket: 'finance-app-85342.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3FKlferzd_jA4n7dRRyNm5F0ty9s4fs',
    appId: '1:497229688858:web:0a5b994c3da0e3d8fba1a3',
    messagingSenderId: '497229688858',
    projectId: 'finance-app-85342',
    authDomain: 'finance-app-85342.firebaseapp.com',
    storageBucket: 'finance-app-85342.firebasestorage.app',
  );
}
